### ISSUE TITLE
Elaborar detalhamento dos componentes.

### ISSUE THREAD

**Issue by tmsasaki** [giovannigv/ppads-projeto-05K#16]
1. Execute o Git Bash.

2. Caso ainda não tenha feito o clone, execute (lembre-se de substituir USUARIO):

    git clone https://github.com/USUARIO/ppads-projeto-05K

3. Acesse o diretório de trabalho:

    cd ppads-projeto-05K

4. Adicione o repositório do professor como upstream:

    git remote add upstream https://github.com/tmsasaki/ppads-projeto-05K

5. Atualize a sua cópia de trabalho:

    git fetch upstream
    git checkout master
    git rebase upstream/master

6. Atualize o seu repositório:

    git push –f origin master

7. Atualize o documento que está na pasta docs/4-componentes.

**Comment by giovannigv** [comment]
commit 632a724
