### ISSUE TITLE
Na seção "Integração com outros sitemas" (1): realmente será feita a integração com o sistema de cada lanchonete? Ela precisaria ser realizada caso-a-caso, uma vez que cada lanchonete pode ter um sistema diferente.

### ISSUE THREAD

**Issue by tmsasaki** [giovannigv/ppads-projeto-05K#2]

**Comment by tmsasaki** [comment]
O documento de visão ainda menciona a integração com o sistema da lanchonete. No entanto, creio que esta não é uma integração viável como parte deste projeto, uma vez que cada lanchonete deve possuir um sistema diferente.

**Comment by KitoVallim** [comment]
Não haverá integração com o sistema de outras lanchonetes, as lanchonetes irão interagir com o nosso sistema. Farão login no nosso software.
